---
namespace: osodevops
name: kafka_platform
version: 1.0.1
readme: README.md
authors:
  - OSO <info@osodevops.io>
description: >-
  Production-ready Apache Kafka deployment with KRaft consensus,
  TLS/SASL security, and full monitoring stack (Prometheus, Grafana, Kafka UI).
license_file: LICENSE
tags:
  - kafka
  - streaming
  - kraft
  - monitoring
  - prometheus
  - grafana
  - security
  - tls
  - sasl
  - scram
dependencies:
  ansible.posix: "*"
  community.general: ">=5.0.0"
  community.crypto: ">=2.0.0"
repository: https://github.com/osodevops/ansible_kafka_platform
documentation: https://github.com/osodevops/ansible_kafka_platform/blob/main/README.md
homepage: https://oso.sh/fully-managed-kafka/
issues: https://github.com/osodevops/ansible_kafka_platform/issues
build_ignore:
  - .github
  - .gitignore
  - molecule
  - examples
  - docs
  - Makefile
  - "*.tar.gz"
  - venv
  - __pycache__
  - requirements.txt
