#!/usr/bin/env bash
# setup-airgap-repo.sh
# =====================
# Sets up a simple HTTP file server from the air-gap bundle directory.
# Run this on the air-gapped control node or internal repository server.
#
# Usage:
#   ./scripts/setup-airgap-repo.sh --bundle-dir /opt/oso-kafka-airgap-bundle-20260324
#   ./scripts/setup-airgap-repo.sh --bundle-dir /opt/bundle --port 9090
#   ./scripts/setup-airgap-repo.sh --bundle-dir /opt/bundle --generate-inventory
#   ./scripts/setup-airgap-repo.sh --bundle-dir /opt/bundle --systemd

set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { echo -e "\033[36m[INFO]\033[0m  $*"; }
ok()    { echo -e "\033[32m[OK]\033[0m    $*"; }
warn()  { echo -e "\033[33m[WARN]\033[0m  $*"; }
fail()  { echo -e "\033[31m[FAIL]\033[0m  $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
BUNDLE_DIR=""
PORT="8080"
MODE="serve"     # serve | systemd | generate-inventory | setup-os-repo
HOSTNAME_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bundle-dir)
      BUNDLE_DIR="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --hostname)
      HOSTNAME_OVERRIDE="$2"
      shift 2
      ;;
    --systemd)
      MODE="systemd"
      shift
      ;;
    --generate-inventory)
      MODE="generate-inventory"
      shift
      ;;
    --setup-os-repo)
      MODE="setup-os-repo"
      shift
      ;;
    -h|--help)
      cat << 'HELPEOF'
Usage: setup-airgap-repo.sh --bundle-dir <path> [OPTIONS]

Sets up an internal HTTP repository for air-gapped Kafka deployment.

Options:
  --bundle-dir <path>      Path to the extracted air-gap bundle (required)
  --port <port>            HTTP server port (default: 8080)
  --hostname <hostname>    Override hostname for generated URLs
  --systemd                Generate and install a systemd service file
  --generate-inventory     Print inventory variable overrides for air-gap
  --setup-os-repo          Create apt/yum repository index from os-packages/
  -h, --help               Show this help

Examples:
  # Start serving immediately
  ./setup-airgap-repo.sh --bundle-dir /opt/bundle

  # Generate a systemd unit for production use
  ./setup-airgap-repo.sh --bundle-dir /opt/bundle --systemd

  # Print inventory variables to paste into group_vars
  ./setup-airgap-repo.sh --bundle-dir /opt/bundle --generate-inventory
HELPEOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$BUNDLE_DIR" ]]; then
  echo "Error: --bundle-dir is required" >&2
  exit 1
fi

BUNDLE_DIR="$(cd "$BUNDLE_DIR" && pwd)"

if [[ ! -d "$BUNDLE_DIR" ]]; then
  fail "Bundle directory not found: $BUNDLE_DIR"
fi

REPO_HOST="${HOSTNAME_OVERRIDE:-$(hostname -f 2>/dev/null || hostname)}"
REPO_URL="http://${REPO_HOST}:${PORT}"

# ---------------------------------------------------------------------------
# Mode: Generate inventory variables
# ---------------------------------------------------------------------------
if [[ "$MODE" == "generate-inventory" ]]; then
  # Detect versions from filenames
  KAFKA_TGZ=$(find "${BUNDLE_DIR}/kafka" -name "kafka_*.tgz" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")
  JMX_JAR=$(find "${BUNDLE_DIR}/jmx" -name "jmx_prometheus_javaagent-*.jar" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")
  PROM_TGZ=$(find "${BUNDLE_DIR}/prometheus" -name "prometheus-*.tar.gz" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")
  GRAFANA_TGZ=$(find "${BUNDLE_DIR}/grafana" -name "grafana-*.tar.gz" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")
  UI_JAR=$(find "${BUNDLE_DIR}/kafka-ui" -name "*.jar" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")

  cat << EOF
---
# Air-Gapped Deployment Configuration
# =====================================
# Generated by setup-airgap-repo.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Internal repository: ${REPO_URL}
#
# Copy this file to: inventory/group_vars/all/airgap.yml

# Core air-gap toggle
airgap_enabled: true
airgap_repo_url: "${REPO_URL}"

# Apache Kafka binary
kafka_download_url: "${REPO_URL}/kafka/${KAFKA_TGZ}"

# JMX Prometheus JavaAgent
jmx_exporter_download_url: "${REPO_URL}/jmx/${JMX_JAR}"

# Prometheus
prometheus_binary_url: "${REPO_URL}/prometheus/${PROM_TGZ}"

# Grafana (tarball method for air-gap)
grafana_install_method: "tarball"
grafana_tarball_url: "${REPO_URL}/grafana/${GRAFANA_TGZ}"

# Kafbat UI
kafka_ui_download_url: "${REPO_URL}/kafka-ui/${UI_JAR}"
EOF
  exit 0
fi

# ---------------------------------------------------------------------------
# Mode: Setup OS package repository index
# ---------------------------------------------------------------------------
if [[ "$MODE" == "setup-os-repo" ]]; then
  OS_PKG_DIR="${BUNDLE_DIR}/os-packages"

  if [[ ! -d "$OS_PKG_DIR" ]] || [[ -z "$(ls -A "$OS_PKG_DIR" 2>/dev/null)" ]]; then
    fail "No OS packages found in ${OS_PKG_DIR}/"
  fi

  # Detect package type
  if ls "${OS_PKG_DIR}"/*.deb >/dev/null 2>&1; then
    info "Detected .deb packages — creating APT repository index..."
    if ! command -v dpkg-scanpackages >/dev/null 2>&1; then
      fail "dpkg-scanpackages not found. Install dpkg-dev: apt install dpkg-dev"
    fi
    cd "$OS_PKG_DIR"
    dpkg-scanpackages ./ /dev/null | gzip > Packages.gz
    cd - > /dev/null
    ok "APT repository index created"
    echo ""
    echo "Add this to managed nodes:"
    echo "  echo 'deb [trusted=yes] ${REPO_URL}/os-packages/ ./' > /etc/apt/sources.list.d/oso-kafka-offline.list"

  elif ls "${OS_PKG_DIR}"/*.rpm >/dev/null 2>&1; then
    info "Detected .rpm packages — creating YUM repository index..."
    if ! command -v createrepo >/dev/null 2>&1 && ! command -v createrepo_c >/dev/null 2>&1; then
      fail "createrepo not found. Install: yum install createrepo_c"
    fi
    CREATEREPO=$(command -v createrepo_c || command -v createrepo)
    "$CREATEREPO" "$OS_PKG_DIR"
    ok "YUM repository index created"
    echo ""
    echo "Add this to managed nodes:"
    echo "  cat > /etc/yum.repos.d/oso-kafka-offline.repo << 'REPOEOF'"
    echo "  [oso-kafka-offline]"
    echo "  name=OSO Kafka Platform Offline Repository"
    echo "  baseurl=${REPO_URL}/os-packages/"
    echo "  enabled=1"
    echo "  gpgcheck=0"
    echo "  REPOEOF"
  else
    fail "No .deb or .rpm packages found in ${OS_PKG_DIR}/"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Mode: Generate systemd service
# ---------------------------------------------------------------------------
if [[ "$MODE" == "systemd" ]]; then
  SERVICE_FILE="/etc/systemd/system/oso-airgap-repo.service"

  info "Creating systemd service: $SERVICE_FILE"

  cat > /tmp/oso-airgap-repo.service << EOF
[Unit]
Description=OSO Kafka Air-Gap Repository Server
After=network.target

[Service]
Type=simple
WorkingDirectory=${BUNDLE_DIR}
ExecStart=/usr/bin/python3 -m http.server ${PORT} --bind 0.0.0.0
Restart=always
RestartSec=5
User=nobody
Group=nogroup

[Install]
WantedBy=multi-user.target
EOF

  if [[ $EUID -eq 0 ]]; then
    cp /tmp/oso-airgap-repo.service "$SERVICE_FILE"
    systemctl daemon-reload
    systemctl enable --now oso-airgap-repo.service
    ok "Service installed and started"
    echo ""
    echo "  Status:  systemctl status oso-airgap-repo"
    echo "  Logs:    journalctl -u oso-airgap-repo -f"
    echo "  URL:     ${REPO_URL}"
  else
    echo ""
    warn "Not running as root. Service file written to /tmp/oso-airgap-repo.service"
    echo "  Install with:"
    echo "    sudo cp /tmp/oso-airgap-repo.service ${SERVICE_FILE}"
    echo "    sudo systemctl daemon-reload"
    echo "    sudo systemctl enable --now oso-airgap-repo"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Mode: Serve (default) — start HTTP server in foreground
# ---------------------------------------------------------------------------
info "Starting HTTP file server..."
echo ""
echo "  Serving:  ${BUNDLE_DIR}"
echo "  URL:      ${REPO_URL}"
echo "  Press Ctrl+C to stop"
echo ""

cd "${BUNDLE_DIR}"
exec python3 -m http.server "${PORT}" --bind 0.0.0.0
